# Facebook API credentials
# These credentials are required to authenticate with the Facebook Marketing API
facebook:
  # Application ID from Facebook Developers Console
  app_id: ''
  # Application secret key from Facebook Developers Console
  app_secret: ''
  # Access token with permissions to manage campaigns
  # This token must have ads_management permission
  access_token: ''

# Timezone configuration (optional, defaults to Asia/Jerusalem if not specified)
timezone: 'Asia/Jerusalem'

# Account settings
account:
  id: 'act_'  # Facebook Ad Account ID , **not** required as long as you have the campaign ids

# Campaign management configuration
campaigns:
  # List of Facebook campaign IDs to manage
  # These campaigns will be activated/paused according to the schedule
  managed_campaigns:
    - ''  # Example campaign ID
    - ''  # Example campaign ID
  
  # Campaign status definitions
  status:
    active: 'ACTIVE'    # Status when campaign should run
    paused: 'PAUSED'    # Status when campaign should stop
    valid_statuses:     # All possible campaign statuses from Facebook API
      - 'ACTIVE'
      - 'PAUSED'
      - 'DELETED'
      - 'ARCHIVED'
  
  # Weekly schedule configuration
  # ---------------------------------------------------------------
  # Format:
  #   day_of_week:
  #     start_time: 'HH:MM'  # 24-hour format in UTC timezone
  #     end_time: 'HH:MM'    # 24-hour format in UTC timezone
  #     enabled: true/false  # Optional, defaults to true
  #
  # Required fields per day:
  #   - start_time: Time to activate campaigns (format: 'HH:MM')
  #   - end_time: Time to pause campaigns (format: 'HH:MM')
  #
  # Optional fields:
  #   - enabled: Set to false to keep campaigns paused all day
  #
  # Notes:
  #   - All times must be in UTC timezone
  #   - Times must be in 24-hour format with leading zeros
  #   - Valid time range: '00:00' to '23:59'
  #   - start_time must be before end_time
  #   - If a day is missing, it's treated as disabled
  #   - Setting enabled: false is equivalent to removing the day
  # ---------------------------------------------------------------
  
  schedule:
    # Default schedule settings (used if day-specific settings are missing)
    defaults:
      start_time: '09:00'
      end_time: '17:00'
      enabled: true
    
    monday:
      start_time: '08:00'
      end_time: '17:00'
      enabled: true
    
    tuesday:
      start_time: '09:00'
      end_time: '17:00'
    
    wednesday:
      start_time: '09:00'
      end_time: '17:00'
    
    thursday:
      start_time: '09:00'
      end_time: '17:00'
    
    friday:
      start_time: '09:00'
      end_time: '16:00'
    
    saturday:
      start_time: '10:00'
      end_time: '15:00'
    
    sunday:
      start_time: '14:50'
      end_time: '14:55'

  # Time format settings
  time:
    format: '%H:%M'         # Time format for internal processing
    display_format: 'HH:MM' # Time format for display in logs
    days_order:            # Order of days for schedule processing
      - 'monday'
      - 'tuesday'
      - 'wednesday'
      - 'thursday'
      - 'friday'
      - 'saturday'
      - 'sunday'

  # Examples of alternative configurations:
  # -------------------------------------
  # Workdays only:
  #   monday through friday: 09:00-17:00
  #   saturday and sunday: disabled
  #
  # Custom hours per day:
  #   monday: 09:00-17:00
  #   tuesday: 08:00-18:00
  #   wednesday: 09:00-16:00
  #   thursday: 10:00-19:00
  #   friday: 09:00-15:00
  #   weekend: disabled
  #
  # 24/7 except Sunday:
  #   monday through saturday: 00:00-23:59
  #   sunday: disabled 

# Error handling configuration
errors:
  retry:
    max_attempts: 3        # Maximum number of retry attempts
    delay_seconds: 5       # Delay between retries
    exponential_backoff: true  # Increase delay time between retries
  
  logging:
    api_errors: 'ERROR'    # Log level for API errors
    schedule_errors: 'WARNING'  # Log level for schedule parsing errors
    status_changes: 'INFO'     # Log level for campaign status changes
  
  handling:
    continue_on_error: true    # Continue execution after non-critical errors
    alert_on_consecutive_failures: 3  # Alert after X consecutive failures 

# System configuration
system:
  # Monitoring interval
  check_interval: 300  # Time between checks in seconds (5 minutes)
  
  # Logging configuration
  logging:
    file: 'campaign_manager.log'
    format: '%(asctime)s - %(levelname)s - %(message)s'
    level: 'INFO'
    max_size: 10485760  # 10MB
    backup_count: 5 
